# Generated by Django 6.0.6 on 2026-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
