# Generated by Django 6.0.6 on 2026-06-30 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='share_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
