# Generated by Django 6.0.6 on 2026-06-30 07:53

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='expiry_date',
            field=models.DateTimeField(default=files.models.default_expiry),
        ),
    ]
